services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-4.3.2-management}
    container_name: rabbitmq
    hostname: rabbitmq_node
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: passwd

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      start_period: 10s
      start_interval: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:${POSTGRES_VERSION:-18.4}
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=db1
    volumes:
      - ./postgres/init-db:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer:${ADMINER_VERSION:-5.4.2}
    container_name: adminer
    ports:
      - 8081:8080
    links:
      - postgres:db
    depends_on:
      - postgres

  init-volume:
    image: alpine
    volumes:
      - python-hydra-output:/python/output/hydra
      - python-mock-output:/python/output/mock
    command: chown -R 888:888 /python/output

  python-app:
    container_name: python-app
    user: "888:888"

    profiles:
      - python-local
      - local

    build:
      context: ../python
      dockerfile: Dockerfile
      args:
        - MAIN_FILE=main.py
    
    environment:
      UV_NO_DEV: 0
      UV_NO_ENV_FILE: true
      PYTHON_APP_PROFILE: compose
    
    secrets:
      - google-api-key

    volumes:
      - python-hydra-output:/app/outputs
      - python-mock-output:/app/resources/mock

    # https://docs.docker.com/compose/how-tos/file-watch/
    # https://docs.docker.com/reference/compose-file/develop/
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app
          include:
            - "*.py"
          ignore:
            - .venv/
          initial_sync: true

        - action: rebuild
          path: uv.lock

    depends_on:
      rabbitmq:
        # condition: service_started
        condition: service_healthy
        # condition: service_completed_successfully
      init-volume:
        condition: service_completed_successfully

  spring-boot:
    profiles:
      - spring-boot
      - local
    image: stroyteller:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    depends_on:
      python-app:
        condition: service_started

secrets:
  google-api-key:
    file: ./.google-api-key

volumes:
  python-hydra-output:
  python-mock-output: