defaults:
  - _self_
  - agent:
    - editor#1
    - writer#1
  - rabbitmq:
    - common
  
rabbitmq:
  connection:
    _target_: messaging.RabbitHostConfig
    host: rabbitmq
    username: admin
    password: passwd

postgres:
  connection:
    _target_: database.PostgresHostConfig
    host: postgres
    username: admin
    password: passwd
    database: db1

google-genai:
  mock: false
  mock-path: /app/resources/mock/google-genai

background-task:
  google-batach-job:
    interval: 60